import type { CheckIssue } from "../deliverables/check.ts";
import type { Claim, Deliverable, RawSection } from "../deliverables/schema.ts";
import type { EvidenceItem, EvidenceLog } from "../evidence/schema.ts";
import type { EvidenceProfile } from "../evidence/validate.ts";
import { CONFIDENCE_RULES } from "../confidence/rules.ts";

export type { CheckIssue, Claim, Deliverable, RawSection, EvidenceItem, EvidenceLog, EvidenceProfile };

export interface SampleSummary {
  name: "strong" | "mixed" | "thin";
  label: string;
  blurb: string;
  log: EvidenceLog;
  profile: EvidenceProfile;
}

export interface ServerConfig {
  live: boolean;
  model: string | null;
  deliverables: { id: "strategy" | "roadmap"; title: string }[];
  recorded: Record<string, string[]>;
}

/** Events streamed from /api/generate (pipeline events plus server meta). */
export type StreamEvent =
  | { type: "meta"; recorded: boolean; notice?: string; log: EvidenceLog }
  | { type: "start"; run_id: string; deliverable: string; provider: string; model: string; prompt_versions: string[]; profile: EvidenceProfile }
  | { type: "attempt"; attempt: number; max_attempts: number }
  | { type: "draft_section"; attempt: number; section: RawSection }
  | { type: "retry"; attempt: number; issues: CheckIssue[] }
  | { type: "done"; deliverable: Deliverable; attempts: number; usage: { input_tokens: number; output_tokens: number; latency_ms: number } }
  | { type: "failed"; message: string; issues: CheckIssue[]; attempts: number }
  | { type: "error"; message: string };

export class RequestError extends Error {
  constructor(message: string, readonly issues?: { path: string; message: string }[]) {
    super(message);
  }
}

export async function streamGenerate(
  body: unknown,
  onEvent: (e: StreamEvent) => void,
  signal: AbortSignal,
): Promise<void> {
  const res = await fetch("/api/generate", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
    signal,
  });
  if (!res.ok || !res.body) {
    const err = (await res.json().catch(() => ({ error: `Request failed (${res.status})` }))) as { error: string; issues?: { path: string; message: string }[] };
    throw new RequestError(err.error, err.issues);
  }
  const reader = res.body.pipeThrough(new TextDecoderStream()).getReader();
  let buffer = "";
  for (;;) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += value;
    let idx;
    while ((idx = buffer.indexOf("\n\n")) >= 0) {
      const chunk = buffer.slice(0, idx);
      buffer = buffer.slice(idx + 2);
      if (chunk.startsWith("data: ")) onEvent(JSON.parse(chunk.slice(6)));
    }
  }
}

export const confidenceLabel = (c: "high" | "medium" | "low") => CONFIDENCE_RULES[c].label;

export const SOURCE_LABELS: Record<string, string> = {
  interview: "Interviews",
  survey: "Survey",
  analytics: "Analytics",
  usability_test: "Usability test",
  experiment: "Experiment",
  support_tickets: "Support tickets",
  sales_call: "Sales call",
  stakeholder: "Stakeholder view",
  market_research: "Market research",
  competitive_analysis: "Competitive analysis",
  technical_review: "Technical review",
  desk_research: "Desk research",
  anecdote: "Anecdote",
};

export const READINESS: Record<Deliverable["readiness"], { label: string; detail: string }> = {
  ready: { label: "Evidence supports a plan", detail: "Most claims rest on high-confidence evidence." },
  partial: { label: "Partly supported", detail: "Some directions are clear; others are bets to test or conflicts to resolve." },
  insufficient_evidence: {
    label: "Not enough evidence yet",
    detail: "VERA is holding back. Treat everything here as hypotheses and close the gaps first.",
  },
};

export interface ReviewState {
  approved: Record<string, string>; // section id → ISO time
  edits: Record<string, string>; // claim id → edited text
}

export function toMarkdown(d: Deliverable, title: string, client: string, review: ReviewState, model: string): string {
  const approvedCount = d.sections.filter((s) => review.approved[s.id]).length;
  const final = approvedCount === d.sections.length;
  const lines = [
    `# ${title}: ${client}`,
    ``,
    final
      ? `> **Approved.** Every section was reviewed and approved by a person.`
      : `> **Draft for review.** ${approvedCount} of ${d.sections.length} sections approved. VERA proposes; a person decides.`,
    `> Readiness: ${READINESS[d.readiness].label}. Generated by VERA (${model}).`,
    ``,
  ];
  for (const s of d.sections) {
    lines.push(`## ${s.title}${review.approved[s.id] ? " ✓" : " (draft)"}`, ``);
    if (s.claims.length === 0) lines.push(`_${s.note ?? "No supportable claims yet."}_`, ``);
    for (const c of s.claims) {
      const text = review.edits[c.id] ?? c.text;
      const action = c.action ? ` · ${c.action}` : "";
      const edited = review.edits[c.id] ? " · edited" : "";
      lines.push(`- ${text} _[${confidenceLabel(c.confidence)}${action}${edited} · ${c.evidence_ids.join(", ")}]_`);
    }
    lines.push(``);
  }
  if (d.conflicts.length) {
    lines.push(`## Conflicts in the evidence`, ``);
    for (const c of d.conflicts) lines.push(`- **${c.evidence_ids.join(" vs ")}**: ${c.description} _Resolve by:_ ${c.how_to_resolve}`);
    lines.push(``);
  }
  if (d.gaps.length) {
    lines.push(`## Evidence gaps`, ``);
    for (const g of d.gaps) lines.push(`- **${g.missing}**: ${g.why_it_matters} _Would raise confidence:_ ${g.would_raise_confidence}`);
    lines.push(``);
  }
  return lines.join("\n");
}
